---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Сайт должен иметь мобильную версию.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
implicit:
  - Корзина хранится в сессии браузера.
  - Оформление заказа с переходом на страницу оплаты. Каким образом происходит оплата?
  - Нет регистрации на сайте с вводом е-мэйла, логина, пароля, номера телефона
  - Нет информации о том, что сайт должен быть на 2х языках
