---
functional:
  - Разработать интерфейс магазина по продаже товаров с просмотром, фильтрацией товаров и добавлением их в корзину.
  - Пользователь может просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом.
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге.
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Ключевой возможностью магазина будет адаптивная верстка, чтобы он был удобным на мобильных устройствах.
  - SPA приложение, которое не перезагружает страницу.
  - Сайт должен быть доступен на различных устройствах.
  - Корзина хранится в сессии браузера.
  - Сайт должен иметь мобильную версию.
implicit:
  - Регистрация на сайте
  - Личный кабинет
  - Оплата не реализована (картой на сайте, после получения, после согласования с менеджером и тп)
  - Сайт реализован на 2х языках, этого нет в ТЗ
  - В русской версии сайта все должно быть переведено на русский язык
  - Нельзя выбрать все категории товара после того, как была выбрана одна из них. Надо перезагружать сайт
  - Поиск по бренду товара, нет в ТЗ
  - В поиске товара по бренду бренды должны быть расположены в алфавитном порядке
  - Нет перехода по логотипу сайта на главную страницу
  - Цены в долларах в русскоязычной версии сайта
  - Если отжать кнопку "в наличии", все товары пропадают
  - При выборе русского языка не переводятся названия и описание товаров
  - Фото товаров непропорционально растянуты
  - При оформлении заказа товары не пропадают из корзины
  - Информация об остатках товара на складе. Об этом нет информации в ТЗ.
  - Странная постраничная верстка. На одной странице одни товары с одним выбором категорий, на другой - другие
  - При фильтрации по цене дожлжны выводиться товары с окончательной ценой, а не первоначальной
