----
functional:
  - Разработать интерфейс магазина по продаже товаров с просмотром, фильтрацией товаров и добавлением их в корзину.
  - Пользователь может просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом.
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге.
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты. 
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Сайт должен иметь мобильную версию.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Ключевой возможностью магазина будет адаптивная верстка, чтобы он был удобным на мобильных устройствах. 
  - SPA приложение, которое не перезагружает страницу.
  - Сайт должен быть доступен на различных устройствах.
  - Корзина хранится в сессии браузера.
implicit:
  - Нет регистрации на сайте с вводом е-мэйла, логина, пароля, номера телефона
  - Оформление заказа с переходом на страницу оплаты. Оплата не реализована
  - Нет информации о том, что сайт должен быть на 2х языках
  - Нельзя выбрать все категории товара после того, как была выбрана одна из них. Надо перезагружать сайт
  - Нет перехода по логотипу сайта на главную страницу
  - Цены в долларах в русскоязычной версии сайта
  - Фото товаров просто ужасны =) непропорционально растянуты
  - Если отжать кнопку "в наличии", все товары пропадают
  - При выборе русского языка не переводятся названия и описание товаров
  - Странная постраничная верстка. На одной странице одни товары, с одним выбором категорий, на другой - другие
  - При оформлении заказа товары не пропадают из корзины
  - Остаток товара на складе - лишняя деталь в коризине
